### ISSUE TITLE
一般ユーザーと管理者を区別したい

### ISSUE THREAD

**Issue by nekocatchan** [nekocatchan/quiz-server#10]
一般ユーザーと管理者を区別して、アクセスできるAPIを制限したい。

ユーザーに role を持たせると良さそう。値は "user" や "admin" などにすると良さそう

```
{ username: "john-doe", passwordHash: "brabrabra", role: "admin" }
```

登録時の inviteCode で分岐する？

**Comment by Shion-Serizawa** [comment]
adminのときだけ，roleキーを増やすでも問題はなさそう．（どうせオブジェクトで保存するので）

個人的にはrole必須 or adminだけはどっちでもいい．
ただ，どこでバリデーションするんだ？router近辺でroleに関するバリデーションができる？

**Comment by nekocatchan** [comment]
こんな感じにできそう

```
router.get(
    "/foobar",
    (ctx, next) => {
        // role を検証。だめなら return する
        
        // 大丈夫ならコントローラーの処理をする
        next();
    },
    Controller.action,
)
```

**Comment by nekocatchan** [comment]
#26 で準備だけした
