### ISSUE TITLE
Cookie を暗号化する

### ISSUE THREAD

**Issue by nekocatchan** [nekocatchan/quiz-server#14]
今は username=john-doe のように保存しているので、APIを直接叩いてなりすましをする人がいるかもしれない

**Comment by Shion-Serizawa** [comment]
優先度としては後回しだと考える．

（このリポジトリが監視されていなければ）会場でこのサービスが初お披露目なので，変なことはされないやろ．
要するに，jig社員の治安の良さを信じる．

まぁ，忘年会後はおそろしいデバッグをされる可能性はあるが🙈
