### ISSUE TITLE
問題をGETするときに答えが出ちゃう

### ISSUE THREAD

**Issue by Shion-Serizawa** [nekocatchan/quiz-server#16]
[https://github.com/nekocatchan/quiz-server/pull/13](https://github.com/nekocatchan/quiz-server/pull/13)にて，GET /questions/:questionId を作成したが，正解のデータも含めて返している．

そのため，うまい分岐を考える必要がある．
（関係ないけど，postmanを初めて使ったけど，便利）

**Comment by nekocatchan** [comment]
次のようにできそう

```
const o = { propA: "public", propB: "public", propC: "TOP_SECRET" };
const pick = ({ propA, propB }) => ({ propA, propB });
response.body = pick(o);
```
